### PR TITLE
Ignore protocol header if handler did not specify allowed protocols

### LINKED ISSUE #27: Crash when request has 'Sec-WebSocket-Protocol' header but protocols wasn't passed.
We currently require passing a `protocols` argument if the callback function takes 2 arguments, and allow it otherwise. If protocols are omitted it will fail with a confusing error if a request contains a protocol header. `NoSuchMethodError: The method 'contains' was called on null.`

We should either decide it's OK to silently ignore the header, or we should throw a more specific error.

### PR DESCRIPTION
**Pull request by natebosch**
Closes #27

The spec says "if the server does not agree to any of the client's
requested subprotocols, the only acceptable value is null". The mozilla
docs for implementing a web socket server say "The client may close the
connection if it doesn't get the subprotocol it wants."

From this I take it that the safest thing to do is to ignore the
protocols. A server which wants to be more careful can handle the `null`
protocol in whatever way makes sense.

### CODE REVIEW

File: lib/src/web_socket_handler.dart [hunk 1]
```diff
@@ -94,6 +94,7 @@ class WebSocketHandler {
   String _chooseProtocol(Request request) {
     var protocols = request.headers['Sec-WebSocket-Protocol'];
```
Comment (jakemac53) [inline lib/src/web_socket_handler.dart:95]: consider renaming this to `requestProtocols` so the difference between these is more clear

**Review by jakemac53 — APPROVED** [review]
